# Generated by Django 4.2 on 2023-04-29 13:25

import admin_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0014_delete_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, verbose_name='Product Code')),
                ('product_qty', models.BigIntegerField(null=True, verbose_name='Available Stock')),
                ('reseller_name', models.CharField(max_length=200, null=True, verbose_name='Reseller Name')),
                ('reason', models.TextField(null=True, verbose_name='Reason')),
                ('return_date', models.CharField(max_length=200, null=True, verbose_name='Return Date')),
                ('return_status', models.CharField(choices=[('', ''), ('returned', 'returned'), ('unreturned', 'unreturned')], max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('star_rating', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Settings_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_category', models.CharField(max_length=250, null=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Settings_flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_flavor', models.CharField(max_length=250, null=True, verbose_name='Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Settings_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_unit', models.CharField(max_length=250, null=True, verbose_name='Unit')),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AddField(
            model_name='by_batch',
            name='product_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='OrderItem_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_flavor',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Flavor'),
        ),
        migrations.AlterField(
            model_name='by_batch',
            name='product_quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cart_payment',
            name='cart_change',
            field=models.BigIntegerField(null=True, verbose_name='change'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available'), ('low stock', 'low stock')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='img/default_profile.jpg', null=True, upload_to=admin_site.models.image_path, verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
